search:
 url: https://search.smzdm.com/?c=faxian&s={key}&order=time&v=b
 keywords: 
  url: https://github.com/jy1989/SmzdmCrawler/issues/2
 to: 接收邮箱名
 delay:
  milliseconds: 15000
spring:
 mail:
  host: smtp.qq.com
  username: qq邮箱名
  password: qq邮箱授权码
  properties:
   smtp:
    auth: true
 
 

